pdf:
	pdflatex Probability-Notes-1.tex
	pdflatex Probability-Notes-1.tex
	pdflatex Probability-Notes-1.tex
	rm Probability-Notes-1.log
	rm Probability-Notes-1.aux

	pdflatex Probability-Notes-2.tex
	pdflatex Probability-Notes-2.tex
	pdflatex Probability-Notes-2.tex
	rm Probability-Notes-2.log
	rm Probability-Notes-2.aux

clean:
	rm Probability-Notes-1.pdf 
	rm Probability-Notes-2.pdf 