# Syllabus {-} 


## Course Information {-}

- Spring Semester, 2022
- Course Dates: Jan. 10 - May 4, 2022
- Course Time: MW 3:00 - 4:15 PM 
- Course Room: Huntsman Hall 326
- [Slack Channel]()
- [Course Canvas]()


## Instructor Information {-}

- [Tyler J. Brough](broughtj.github.io)
- Office Hours: By Appointment 
- Office: BUS 512
- Email: tyler.brough@usu.edu

## Course Description {-}

This course is the first in a sequence of courses in data analysis for business and economic decision making. The focus of this course
is regression modeling. The approach of the course is applied rather than theoretical. That is, we will focus not just, or even primarily,
on the mathematics of regression modeling but on how to apply and understand these data analysis tools. The goal of the course is for you
to develop deep intuition for how to build and apply regression models.  

The main purpose of the course is to foster three modes of thought to enable you to become 
thoughtful scholars of data analytics:

1. __Computational Logic:__ Computational thinking helps break a problem down and find a practical path to
	 successful implementation. Important techniques from computational mathematics and computational statistics
	 will be introduced as they pertain to data analysis.

2. __Statistical Logic:__ The main focus of the course will be learning to think statistically about problems in
     business analytics. All meaningful problems in data analysis are necessarily embedded in conditions of
	 uncertainty. There exists a core statistical logic that is distinct from the mathematical. Learning
	 to develop this mode of thinking is an essential step in the life of any successful business data analyst.
	 We will find that statistical reasoning is essential for proper business reasoning. 

3. __Economic Logic:__ Arbitrage is the central underlying concept all of economics and finance. Developing
     skills in economic reasoning is an essential element in business data analytics.  


These three ways of thinking are not independent. Quite to the contrary, we will find that they are strongly mutually
reinforcing.  


## Textbook and Other Resources {-}

There is only one _required_ textbook for the course: 

* [Introductory Econometrics: A Modern Approach 5th Edition][Wooldridge]

I will also use some other books for lecture material. Some of these are the following: 

* [An Introduction to Modern Bayesian Econometrics][Lancaster] by Lancaster.

* [Computational Statistics Handbook with MATLAB][MartinezMartinez] by Martinez & Martinez.

* [Introducing Monte Carlo Methods with R][RobertCassella] by Robert & Casella


There will be other readings from academic and trade articles assigned throughout the semester. These will be made available on Canvas.
___This course is reading intensive so please be prepared to read thoroughly and come prepared to discuss those readings.___


## Method of Teaching and Learning {-}

This course will be taught as a graduate seminar style course. __That means that your preparation and participation is crucial.__ We will get out of this course what we individually and collectively put into it. 

We will follow the Socratic Method during lectures. A good amount of class time will also be dedicated to guided computational exploration. The idea behind this exploration is to develop a methodology for __computational thinking__. Mathematical theory will serve as an important background to this enterprise but will not itself be the focus. 

___Your preparation and participation is absolutely essential to the success of this course!___


## Assessment {-} 

The grade that you will earn will be determined by the weighted total points accumulated. The weights given to each part of the class are as follows:

* _Class Preparation & Participation (100%)_ - In a Socratic style seminar student preparation and participation is essential!

* _Computational exercises (10%):_ There will be five main computational exercises to develop software architecture skills that are essential for the practicing data analyst.
  1. Chicken nuggest/coin problem
  2. Guess my number problem
  3. Monte Carlo simulation of pi problem
  4. Cherry tootsie rolls bandit problem
  5. St. Petersburg paradox Monte Carlo simulation

* _Preliminary exam (20%):_ A take-home preliminary exam covering the essentials of probability and mathematical statistics that are essential for regression analysis.

* _Student Presentations (10%)_ - Throughout the course a set of specialized readings will be distributed. Each student will have an opportunity to prepare a presentation to the class on one or more of the assigned readings. 

* _Annotated Bibliography & Wiki-style Articles (10%)_ 
	- Throughout the course, a set of specialized readings will be distributed. Each student will prepare an annotated bibliography of each reading.
	- Students will prepare a Wikipedia-style summary article on one specialized topic from each of the four areas of concentration. The following are examples (not exhaustive) of topics that might be chosen:
		1. Probability & Math Stats: Bayes rule, null hypothesis testing, maximum likelihood, etc.
		2. Computational statistics: Bootstrap methods, sampling-importance resampling (SIR), variance reduction technique, etc.
		3. Regression: least squares, Bayesian regression, etc. 
		4. Advanced topics: supervised learning, classification, loss functions, non-stationary time series, etc.

* _Projects (30%):_
  - Simple linear regression: futures hedging data (15%)
  - Multiple linear regression: stock returns data (15%)

* _Take home final exam (20%):_ there will be a applications-based take-home final exam.

* _Extra Credit:_ There will several opportunities for extra credit work.


## Communications {-}

I will use Canvas somewhat minimally to outline our progress, share documents and other materials, and for uploading content. 

For all other communication purposes we will use a course Slack channel. You will receive an invitation to the Slack the first week of class. You should
check for communications and announcements often. 


## Topics {-}

We will cover the following main modules:

1. Review of Probability and Mathematical Statistics: Appendices A - C
2. Some basic tools from Computational Statistics: handouts
3. Linear regression: Chapters 2 - 8
4. Advanced topics:
  - Regression with time series variables: Chapters 10 - 12
  - Limited dependent variable models: Chapter 17


<br>


***NB:*** I reserve the right to dynamically alter this list as the course progresses. I will announce any such changes in class and on the course Slack channel. 

<br>

### Import Dates {-}

* __First day of classes__ - Jan 10
* __Martin Luther King, Jr. Day__ - Jan 17
* __Presidents' Day__ - Feb 21
* __Spring Break__ - Mar 7 - 11
* __Last day of classes__ - Apr 26
* __Final exams__ - Apr 28 - May 4


[Lancaster]: https://www.wiley.com/en-us/Introduction+to+Modern+Bayesian+Econometrics-p-9781405117203
[MartinezMartinez]: https://www.routledge.com/Computational-Statistics-Handbook-with-MATLAB/Martinez-Martinez/p/book/9781466592735
[RobertCassella]: https://link.springer.com/book/10.1007/978-1-4419-1576-4
[Wooldridge]: https://www.cengage.com/cgi-wadsworth/course_products_wp.pl?fid=M20b&product_isbn_issn=9781111531041