pdf:
	Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'

gitbook:
	Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

epub:
	Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book")'

clean:
	rm -rf build